PE #4 in C

diff --git a/c/pull b/c/pull
--- a/c/pull
+++ b/c/pull
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -eu
 # Pulls a particular problem from projecteuler.net,
 # including the problem description, and creates a
 # a dummy .c file for implementation.
@@ -12,6 +12,18 @@ if [[ $# -ne 1 ]]; then
     exit 1
 fi
 
+
+# print ERROR on any issue
+trap die EXIT
+last_cmd=
+die_msg() { echo "$@"; exit 1; }
+die() { die_msg "ERROR; last_cmd='${last_cmd:-(none)}''"; }
+cmd() { last_cmd="$@"; $@; }
+
+# wget needs to be installed
+hash wget || die_msg "You need to install 'wget'"
+
+# Pull problem N
 c_file=problem_$1.c
 url=https://projecteuler.net/problem=$1
 if [[ -f $c_file ]]; then
@@ -21,7 +33,8 @@ fi
 
 src=`mktemp`
 pbm=`mktemp`
-wget --quiet $url -O $src 2>/dev/null
+
+cmd wget --quiet $url -O $src 2>/dev/null
 
 # read the file and sanitize output
 
@@ -38,6 +51,7 @@ cat << EOF >> $c_file
  * in this directory.
  *
 EOF
+
 
 while read line; do
     echo " * " $line >> $c_file
@@ -63,4 +77,6 @@ solution(void)
 MAIN(solution, SOLUTION);
 EOF
 
-rm $f $pbm
+# end
+rm -f $src $pbm
+trap - EXIT
